import { MouseEventHandler, useState } from 'react';
import Head from 'next/head'
import { LazyImage } from '<olgaabx>/components/RandomFox'
import { random } from 'lodash';

// generate a random function between 1 and 123
const myRandom = () => random(1, 123);

//generate simple unique id
const generateId = () => Math.random().toString(36).substring(2, 9);

export default function Home() {
  const [images, setImages] = useState<Array<IFoxImageItem>>([]);

  const addNewFox: MouseEventHandler<HTMLButtonElement> = () => {
    const newImageItem: IFoxImageItem = {
      id: generateId(), 
      url: `https://randomfox.ca/images/${myRandom()}.jpg`
    }

    setImages([
      ...images,
      newImageItem
    ])
  }
  
  return (
    <>
      <Head>
        <title>React with TypeScript</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl font-bold underline">
          Hello world!
        </h1>
        <button 
        onClick={addNewFox}
        className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full"
        >
          Add new fox
        </button>
        {images.map(({ id, url }) => (
          <div key={id} className='p-4'>
            <LazyImage
            src={url}
            width="320"
            height="auto"
            className="mx-auto rounded-md bg-gray-300"
            onClick={() => {
                console.log("holi!");
            }}
            />
          </div>
        ))}
      </main>
    </>
  )
}